Create the system's front-end
RonnyFrayRegato/predictive-healthcare-infrastructure-tool pull request #2
Opened 2023-02-27 04:09 UTC by RonnyFrayRegato

Create the system's front-end, including React components, routing, and API calls.

2023-04-02 20:06 UTC, AlexisMLopez requested changes
Inconsistent use of white-space and indentation, which makes the code harder to read and follow. Inconsistent naming conventions, such as mixing camelCase and snake_case for variable names, which makes it harder to understand the purpose of each variable or function. Lack of comments and documentation, which makes it harder for other developers to understand the purpose and functionality of the code.

2023-04-02 20:06 UTC, AlexisMLopez commented on phit-ui/src/pages/home-page/home-page.css
Remove unnecessary newlines on lines 1, 24, 33 and 65 to improve readability.

2023-04-02 20:06 UTC, AlexisMLopez commented on phit-ui/src/pages/home-page/home-page.js
Add a 'label' for each input element to improve accessibility.
Change the type of the password input to "password" for better security.
Change the case of Username and Password to lowercase, following JavaScript naming conventions.
Adjust formatting to comply with HTML and JavaScript general style guidelines.

2023-04-02 20:06 UTC, AlexisMLopez commented on phit-ui/src/pages/medical-admin-page/medical-admin-page-allergies.css
> +}
Add newline to comply with general CSS style guidelines.

2023-04-02 20:06 UTC, AlexisMLopez commented on phit-ui/src/pages/medical-admin-page/medical-admin-page-allergies.css
> +
Remove newline to comply with general CSS style guidelines.

2023-04-02 20:06 UTC, AlexisMLopez commented on phit-ui/src/pages/medical-admin-page/medical-admin-page-allergies.css
> +.medical-admin-allergies-body {
Remove dead code on lines 51-53 to improve readability.

2023-04-02 20:06 UTC, AlexisMLopez commented on phit-ui/src/pages/medical-admin-page/medical-admin-page-allergies.css
> +
Remove newline to comply with general CSS style guidelines.

2023-04-02 20:06 UTC, AlexisMLopez commented on phit-ui/src/pages/medical-admin-page/medical-admin-page-allergies.css
> +}
Add newline at end of file.

2023-04-02 20:06 UTC, AlexisMLopez commented on phit-ui/src/pages/medical-admin-page/medical-admin-page-allergies.js
Remove newlines on lines 8, 35, 46, 51, 54, 56, 61, 63, 88, and 99.
Update formatting to comply with HTML and JavaScript general style guidelines.

2023-04-02 20:06 UTC, AlexisMLopez commented on phit-ui/src/pages/medical-admin-page/medical-admin-page-medications.css
> +
Remove newline.

2023-04-02 20:06 UTC, AlexisMLopez commented on phit-ui/src/pages/medical-admin-page/medical-admin-page-medications.css
> +}
Add newline.

2023-04-02 20:06 UTC, AlexisMLopez commented on phit-ui/src/pages/medical-admin-page/medical-admin-page-medications.css
> +
Remove newline.

2023-04-02 20:06 UTC, AlexisMLopez commented on phit-ui/src/pages/medical-admin-page/medical-admin-page-medications.css
> +
Remove newline.

2023-04-02 20:06 UTC, AlexisMLopez commented on phit-ui/src/pages/medical-admin-page/medical-admin-page-medications.css
> +}
Add newline.

2023-04-02 20:06 UTC, AlexisMLopez commented on phit-ui/src/pages/medical-admin-page/medical-admin-page-medications.css
> +}
Add newline at end of file.

2023-04-02 20:06 UTC, AlexisMLopez commented on phit-ui/src/pages/medical-admin-page/medical-admin-page-patients.css
> +
Remove newline.

2023-04-02 20:06 UTC, AlexisMLopez commented on phit-ui/src/pages/medical-admin-page/medical-admin-page-patients.css
> +}
Add newline.

2023-04-02 20:06 UTC, AlexisMLopez commented on phit-ui/src/pages/medical-admin-page/medical-admin-page-patients.css
> +
Remove newline.

2023-04-02 20:06 UTC, AlexisMLopez commented on phit-ui/src/pages/medical-admin-page/medical-admin-page-patients.css
> +
Remove newline.

2023-04-02 20:06 UTC, AlexisMLopez commented on phit-ui/src/pages/medical-admin-page/medical-admin-page-patients.css
> +}
Add newline at end of file.

2023-04-02 20:06 UTC, AlexisMLopez commented on phit-ui/src/pages/medical-admin-page/medical-admin-page-supply.css
> +
Remove newline.

2023-04-02 20:06 UTC, AlexisMLopez commented on phit-ui/src/pages/medical-admin-page/medical-admin-page-supply.css
> +}
Add newline.

2023-04-02 20:06 UTC, AlexisMLopez commented on phit-ui/src/pages/medical-admin-page/medical-admin-page-supply.css
> +
Remove newline.

2023-04-02 20:06 UTC, AlexisMLopez commented on phit-ui/src/pages/medical-admin-page/medical-admin-page-supply.css
> +
Remove newline.

2023-04-02 20:06 UTC, AlexisMLopez commented on phit-ui/src/pages/medical-admin-page/medical-admin-page-supply.css
> +
Remove newline.

2023-04-02 20:06 UTC, AlexisMLopez commented on phit-ui/src/pages/system-admin-page/system-admin-home-page.css
> +
Remove newline.

2023-04-02 20:06 UTC, AlexisMLopez commented on phit-ui/src/pages/system-admin-page/system-admin-home-page.css
> +}
Add newline.

2023-04-02 20:06 UTC, AlexisMLopez commented on phit-ui/src/pages/system-admin-page/system-admin-home-page.css
> +
Remove newline.

2023-04-02 20:06 UTC, AlexisMLopez commented on phit-ui/src/pages/system-admin-page/system-admin-home-page.css
> +
Remove newline.

2023-04-02 20:06 UTC, AlexisMLopez commented on phit-ui/src/pages/system-admin-page/system-admin-home-page.css
> +
Remove newline.

2023-04-02 20:06 UTC, AlexisMLopez commented on phit-ui/src/pages/system-admin-page/system-admin-home-page.css
> +
Remove newline.

2023-04-02 20:06 UTC, AlexisMLopez commented on phit-ui/src/pages/system-admin-page/system-admin-home-page.css
> +
Remove newline.

2023-04-02 20:06 UTC, AlexisMLopez commented on phit-ui/src/pages/system-admin-page/system-admin-home-page.css
> +
Remove newline.

2023-04-02 20:06 UTC, AlexisMLopez commented on phit-ui/src/pages/system-admin-page/system-admin-home-page.css
> +
Remove newline.

2023-04-02 21:12 UTC, zachary-mixson requested changes
fix styling issues.

2023-04-02 21:12 UTC, zachary-mixson commented on phit-ui/src/pages/medical-admin-page/medical-admin-page-medications.js
Remove newlines on lines 8, 35, 46, 51, 54, 56, 61, 63, 88, and 99.
Update formatting to comply with HTML and JavaScript general style guidelines.

2023-04-02 21:12 UTC, zachary-mixson commented on phit-ui/src/pages/medical-admin-page/medical-admin-page-patients.js
Remove newlines on lines 8, 35, 46, 51, 54, 56, 61, 63, 88, and 99.
Update formatting to comply with HTML and JavaScript general style guidelines.

2023-04-02 21:12 UTC, zachary-mixson commented on phit-ui/src/pages/medical-admin-page/medical-admin-page-supply.js
Remove newlines on lines 8, 35, 46, 51, 54, 56, 61, 63, 88, and 99.
Update formatting to comply with HTML and JavaScript general style guidelines.

2023-04-02 22:52 UTC, zachary-mixson approved these changes

2023-04-03 01:08 UTC, RonnyFrayRegato commented on phit-ui/.gitignore
> +# See https://help.github.com/articles/ignoring-files/ for more about ignoring files.
@htbryant1256 Add .vs to the .gitignore.

2023-04-03 01:26 UTC, AlexisMLopez approved these changes

2023-04-03 01:27 UTC, merged